# -*- coding: utf-8 -*-
"""AirQualtiy_X_HealthImpacts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lvvsYpIaEwvJITo8bSajzFUaF15GRGwE
"""

!pip install geodatasets matplotlib-map-utils

# preamble
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import files
import geopandas as gpd
from geodatasets import get_path
from matplotlib_map_utils.core.north_arrow import NorthArrow, north_arrow
from matplotlib_map_utils.core.scale_bar import ScaleBar, scale_bar

"""**WORK BOOK EXPLAINED**

*   Compare non exhaust emissions saved due to BEV adoption PM AND NOX
- This requires finding the base year of emissions and subtracting the difference across the two
*   FOR PM2.5 Emissions i also would like to assess if the total emissions has changed much compared to the base of 2024.
1) PM2.5 will be compared on an exhaust basis - tail pipe : complete
2) PM2.5 will be compared on exhaust+ Non exhasut basis (90% GEN)

check this out: https://assets.publishing.service.gov.uk/media/690465e2cc6b3272b3913194/measurement-of-emissions-from-brake-and-tyre-wear-phase-2.pdf

# Setting up the codebase
"""

sregion= "https://github.com/LumumbaAssumani/EV-growth/raw/main/s_region_df.csv"
dfraw = pd.read_csv(sregion)
dfraw = dfraw.rename(columns={'Unnamed: 0': 'time'})
dfraw['time']=pd.to_datetime(pd.PeriodIndex(dfraw['time'], freq='Q').to_timestamp())
dfraw= dfraw.set_index('time')
### start date of my df data frame is the end the ned which is 2024 Q4which relates to TLV

base_start= pd.to_datetime('2024-10-01', yearfirst=True)
df = dfraw[dfraw.index>=base_start].copy()
df.head(30)

ICEV = 1-df
ICEV.head(10)

###data set for BEV
BEV = df
BEV.head(5)

"""### Total licenced vehicles in terms of volume

"""

### formatting the data so that the year period is a datetime index
TLV_csv = "https://github.com/LumumbaAssumani/EV-growth/raw/main/TLV.csv"
TLV = pd.read_csv(TLV_csv)
TLV['year']=pd.to_datetime(pd.PeriodIndex(TLV['year'], freq='Q').to_timestamp())
TLV.set_index('year', inplace=True)
TLV = TLV.rename(columns={'East': 'East of England'})
#TLV

TLV.index[0].year
TLV.index[-1].year

TLV.iloc[-1]

# calculating CAGR of vehicles

start = TLV.iloc[0]
end = TLV.iloc[-1]
n = TLV.index[-1].year - TLV.index[0].year
CAGR =  (((end/ start)**(1/n))-1 )*100
CAGR = CAGR.round(2)

CAGR

# CAGR for each year 2024 to 2050

year_range = np.arange(TLV.index[-1].year,df.index[-1].year+1)

start_val= TLV.iloc[-1]
results =[]

for year in year_range:
  n_future = year - TLV.index[-1].year
  future_fleet =(((CAGR/100) + 1)**n_future)*start_val
  results.append(future_fleet)
 #future_volume = pd.DataFrame(future_fleet, columns=[year])
  #print(f"Predicted fleet for {year}: {round(future_fleet)}")

# Concatenate the list into one DataFrame with 5 columns
future_volume = pd.concat(results, axis=1)
future_volume.columns = year_range

future_volume

future2050  = future_volume[2050].sum()
baseline2024 = future_volume[2024].sum()
print(future2050,baseline2024)
### this states that 38 milli crs will be o the road how much of those are EV's

future_volume.to_csv('future_volume.csv')
files.download('future_volume.csv')

"""## Creating bubble charts to visualise the data"""

future_volume.index

import plotly.express as px

figsize=(10,8)

# Melt to long format then filter to just 2024 and 2050
plot_df = future_volume.reset_index().melt(id_vars="index", var_name="Year", value_name="Volume")
plot_df.columns = ["Region", "Year", "Volume"]

plot_df = plot_df[plot_df["Year"].isin([2024, 2050])]  # 👈 missing from your code

plot_df["Region_label"] = plot_df["Region"].map(lambda r: f"{r} (CAGR: {CAGR[r]}%)")

fig = px.bar(plot_df,
             x="Region_label",
             y="Volume",
             color="Year",
             barmode="group",
             title="Regional Licensced cars: 2024 vs 2050",
             hover_name="Region_label")

fig.update_layout(
    xaxis_title="Region",
    legend_title="Year",
    xaxis_tickangle=-45
)

fig.show()

import plotly.express as px
import plotly.graph_objects as go

# 1. Define your abbreviation mapping from the note
region_mapping = {
    "East of England": "EoE",
    "East Midlands": "EM",
    "London": "LDN",
    "North East": "NE",
    "North West": "NW",
    "South East": "SE",
    "South West": "SW",
    "West Midlands": "WM",
    "Yorkshire and The Humber": "Y&H"
}

order = plot_df[plot_df["Year"]==2050].sort_values("Volume")["Region"].tolist()

fig = px.bar(plot_df,
             x="Region",
             y="Volume",
             color="Year",
             barmode="group",
             title="Regional licensed cars (Millions): 2024 vs 2050",
             color_discrete_map={2024: "steelblue", 2050: "tomato"})

# Bold CAGR % above each 2050 bar
for region in plot_df["Region"].unique():
    vol_2050 = plot_df[(plot_df["Region"]==region) & (plot_df["Year"]==2050)]["Volume"].values[0]
    fig.add_annotation(
        x=region,
        y=vol_2050,
        text=f"<b>{CAGR[region]}%</b>",
        showarrow=False,
        yshift=10,
        font=dict(size=11)
    )

# Add single CAGR% entry to legend
fig.add_trace(go.Scatter(
    x=[None], y=[None],
    mode="markers",
    marker=dict(symbol="square", size=10, color="black"),
    name="CAGR %",
    showlegend=True
))

# 2. Map the short names for the x-axis display and wrap them in <b> tags for boldness
short_names = [f"<b>{region_mapping.get(reg, reg)}</b>" for reg in order]

fig.update_layout(
    xaxis=dict(
        categoryorder="array",
        categoryarray=order,
        tickmode="array",
        tickvals=order,
        ticktext=short_names,                             # Now contains <b> tags
        title=dict(text="<b>Region</b>", font=dict(size=18)), # Bold title, increased size
        tickfont=dict(size=14),                           # Increased tick size
        tickangle=0                                       # Axis tick angle
    ),
    yaxis=dict(
        title=dict(text="<b>Volume</b>", font=dict(size=18)), # Bold title, increased size
        tickformat=".2s",
        tickfont=dict(size=14),                           # Increased tick size
        tickprefix="<b>",                                 # HTML trick to make y-axis numbers bold
        ticksuffix="</b>"
    ),
    legend_title="Legend"
)

fig.show()

"""### Finding the fraction of ICE and BEV's"""

# 2. Extract those specific Q4 rows into a list
q4_rows_ICEV = []
q4_rows_BEV = []

for year in year_range:
    # This creates the string '2024-10-01', '2030-10-01', etc.
    date_str = f"{year}-10-01"

    # Pull the row from ICEV and add it to our list
    q4_rows_ICEV.append(ICEV.loc[date_str])
    q4_rows_BEV.append(BEV.loc[date_str])

ICEV_frac= pd.concat(q4_rows_ICEV, axis=1)
BEV_frac= pd.concat(q4_rows_BEV, axis=1)

BEV_frac.columns = year_range
ICEV_frac.columns = year_range

ICEV_frac

"""### Volume of BEVS and ICEVS"""

### fraction of ICEV's

ICEV_vol= ICEV_frac * future_volume
BEV_vol = BEV_frac * future_volume
add=ICEV_vol + BEV_vol

check = future_volume/add
check

#cars me up 80% of the vehicle fleet? https://www.racfoundation.org/motoring-faqs/mobility
#sense check
ICEV2050= ICEV_vol[2050].sum()
BEC2050= BEV_vol[2050].sum()
print(ICEV2050,BEC2050)

"""### Weight average of ICE MIX"""

## Proportion of cars owned in England by fuel over last 5 years

petrol_avg = np.mean([61,63,62,61,61])
diesel_avg = np.mean([37,34,34,32,31])

# Calculate weights
total_ice_avg = petrol_avg + diesel_avg
petrol_weight = petrol_avg / total_ice_avg
diesel_weight = diesel_avg / total_ice_avg

print(f"Petrol portion of ICE: {petrol_weight:.2%}")
print(f"Diesel portion of ICE: {diesel_weight:.2%}")

"""#Air quality emission code

Good sources that talk about non exhaust emissions:

https://www.eiturbanmobility.eu/wp-content/uploads/2025/05/41-EIT-Emissions-Report-5a-Digital-1.pdf#page=27.10

https://www.sciencedirect.com/science/article/pii/S1352231020306208?ref=pdf_download&fr=RR-2&rr=9d60b8a46c4157a1

| Fuel Type | NOx (g/km) | PM2.5/10 (g/km) | PM2.5 (g/km) |
| :--- | :--- | :--- | :--- |
| Petrol cars | 0.076 | 0.001 | 0.001 |
| Diesel cars | 0.492 | 0.005 | 0.005 |
"""

# conv miles to km
km = 1.60934

# conv g to tones
g_tonnes = 1*(10**6)

"""##  Distance

taking a national approach for average distanced travelled new data set
 NTS0901a: Annual mileage of cars by fuel type (miles): England, 2002 onwards [notes 1, 2, 3]
2024 values
"""

## annual mileage of cars by fuel type miles converted to km

dist_petrol = 6200 * km
dist_diesel = 8300 *km
dist_BEV = 8900 * km

print(dist_petrol, dist_diesel, dist_BEV)

"""## Area of each region in Km^2

This was taken from the ONS data set. Link: https://geoportal.statistics.gov.uk/datasets/235c70d40c494361bd6b0ddaebdf0bad/about
"""

area_hectares = {
    'East of England': 1958472.14,
    'East Midlands': 1581072.52,
    'London': 159469.74,
    'North East': 867550.73,
    'North West': 1491509.07,
    'South East': 1939992.81,
    'South West': 2438520.35,
    'West Midlands': 1300373.63,
    'Yorkshire and The Humber': 1556035.33
}
# 2. Create the Series
area_hect = pd.Series(area_hectares)

#Convert to km2 (1 km2 = 100 hectares)
area_km2 = area_hect/100

#print("Verified Area Series (km2):")
print(area_km2)

"""## Populationn"""

# Population data per region (Source: User provided image)
# Ordered to match the index of the health impact dataframes
# This was n 2024
regional_population = {
    "East of England": 6576306,
    "East Midlands": 5063164,
    "London": 9089736,
    "North East": 2760678,
    "North West": 7737414,
    "South East": 9642942,
    "South West": 5889695,
    "West Midlands": 6187204,
    "Yorkshire and The Humber": 5672962
}

reg_pop = pd.Series(regional_population)
print(reg_pop)

### trips per region

car_trips = {
    "East of England": 418,
    "East Midlands": 431,
    "London": 168,
    "North East": 348,
    "North West": 365,
    "South East": 404,
    "South West": 449,
    "West Midlands": 376,
    "Yorkshire and The Humber": 396
}
car_trips = pd.Series(car_trips)
print(car_trips)

### the total trips averaged across a year which is 363
## this will help me to calculate the cold emisison starts
### i found a doc with regional https://www.gov.uk/government/statistical-data-sets/national-travel-survey-mid-year-estimates
total_trips = car_trips * reg_pop
total_trips

# Calculate what percentage of total trips are taken by petrol/diesel cars
# Assuming ICEV_frac is a known variable in your code

petrol_trips = ICEV_frac.mul(total_trips, axis=0) * petrol_weight
diesel_trips = ICEV_frac.mul(total_trips, axis=0) * diesel_weight

# Check the output
print(petrol_trips.head())

"""## Nox

###  Exhaust emission factors of NOX
"""

# Hot emission factors (Unit: g/km)
# Based on constant running speed after engine warm-up
petrol_hot_nox = 0.069
diesel_hot_nox = 0.545

# Cold Start Emission Factors (Unit: g/trip)
petrol_cold_start_nox = 0.154
diesel_cold_start_nox = 0.286

"""### ICEV MIX for diesel and petrol"""

# petrol Nox_emission
nox_em_petrol_hot = (dist_petrol* ICEV_vol * petrol_weight * petrol_hot_nox)
nox_em_petrol_cold = (petrol_trips *  petrol_cold_start_nox)


nox_em_diesel_hot = (dist_diesel* ICEV_vol * diesel_weight * diesel_hot_nox)
nox_em_diesel_cold = (diesel_trips *  diesel_cold_start_nox)

### adding the totals
nox_em_diesel = nox_em_diesel_hot.add(nox_em_diesel_cold,axis=0)
nox_em_petrol = nox_em_petrol_hot.add(nox_em_petrol_cold,axis=0)

## total exhaust nox emissions in tonne/year
nox_em_petrol = nox_em_petrol /g_tonnes
nox_em_diesel = nox_em_diesel /g_tonnes
##absolute emissions
total_nox_ICE = nox_em_petrol + nox_em_diesel

total_nox_ICE

EST_NOX_BASE = total_nox_ICE[2024].sum()
EST_NOX_BASE

### standardised emissions in tonnes per year per Km2
petrol_nox_stan = nox_em_petrol.div(area_km2,axis=0)
diesel_nox_stan = nox_em_diesel.div(area_km2,axis=0)
total_nox_stan = total_nox_ICE.div(area_km2,axis=0)

total_nox_stan

"""Change in emissions calculations"""

# Subtract the 2024 column from every other column in the DataFrame
# This performs: 2024 - [each column]
total_nox_ICE_change= total_nox_ICE.rsub(total_nox_ICE[2024], axis=0)
total_nox_ICE_change = total_nox_ICE_change.drop(2024,axis=1).copy()
#total_nox_ICE_change

total_nox_ICE_change

# Standardised change: Baseline (2024) minus each year
nox_petrol_change_stan = petrol_nox_stan.rsub(petrol_nox_stan[2024], axis=0)
nox_diesel_change_stan = diesel_nox_stan.rsub(diesel_nox_stan[2024], axis=0)
nox_total_change_stan = total_nox_stan.rsub(total_nox_stan[2024], axis=0)

# Dropping the 2024 baseline column from each DataFrame
nox_petrol_change_stan = nox_petrol_change_stan.drop(columns=[2024])
nox_diesel_change_stan = nox_diesel_change_stan.drop(columns=[2024])
nox_total_change_stan  = nox_total_change_stan.drop(columns=[2024])

total_nox_ICE_change.T.plot(figsize=(10,6))
plt.title('NOx Emission Reductions vs 2024 Baseline')
plt.xlabel('Year')
plt.ylabel('Tonnes of NOx reduced per year ')
plt.legend(loc='upper left')
plt.show()

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

nox_total_change_stan.drop(index='London').T.plot(ax=ax1)
ax1.set_title('Regions Excluding London')
ax1.set_ylabel('Tonnes NOx reduced per 100 km²')

nox_total_change_stan.loc[['London']].T.plot(ax=ax2, color='green')
ax2.set_title('London')
ax2.set_ylabel('Tonnes NOx reduced per 100 km²')

"""## Particular matter

non  exhaust Em


| Vehicle Type    | PM10 (g/km) | PM2.5 (g/km) |
|-----------------|-------------|--------------|
| ICE Petrol      | 0.0405      | 0.0190       |
| ICE Diesel      | 0.0440      | 0.0205       |
| BEV (90% Regen) | 0.0320      | 0.0148       |

### Exhaust emission Factors
"""

# Based on constant running speed after engine warm-up

# Petrol Hot Exhaust Variables g/km
petrol_hot_pm25 = 0.001
diesel_hot_pm25 = 0.004

# Cold Start Emission Factors (Unit: g/trip)

petrol_cold_start_pm25 = 0.009
diesel_cold_start_pm25 = 0.014

#### NON EXHAUST EMISSIONS got this from the grpa
## PM2.5
pm25_non_em_petrol = 0.0190
pm25_non_em_diesel = 0.0205
pm25_non_em_bev = 0.0148

20/1000

"""Exhaust emissions"""

## PM 2.5 emissions
### emissions in g/year

pm25_em_petrol_ex_hot = (dist_petrol * ICEV_vol * petrol_weight * petrol_hot_pm25)
pm25_em_petrol_ex_cold = (petrol_trips * petrol_cold_start_pm25)

pm25_em_diesel_ex_hot = (dist_diesel * ICEV_vol*diesel_weight * diesel_hot_pm25)
pm25_em_diesel_ex_cold = (diesel_trips * diesel_cold_start_pm25)

#### total hot and cold emissions

pm25_em_petrol_ex = pm25_em_petrol_ex_hot.add(pm25_em_petrol_ex_cold,axis=0)
pm25_em_diesel_ex = pm25_em_diesel_ex_hot.add(pm25_em_diesel_ex_cold,axis=0)


### emissions in tonnes/year
pm25_em_petrol_ex = pm25_em_petrol_ex /g_tonnes
pm25_em_diesel_ex = pm25_em_diesel_ex /g_tonnes
total_pm25_ICE_ex = (pm25_em_petrol_ex + pm25_em_diesel_ex)

### standardised emissions 100km2
petrol_pm25_stan_ex = pm25_em_petrol_ex.div(area_km2,axis=0)
diesel_pm25_stan_ex = pm25_em_diesel_ex.div(area_km2,axis=0)
total_pm25_stan_ex = total_pm25_ICE_ex.div(area_km2,axis=0)

total_pm25_ICE_ex

"""Non exhaust emissions"""

### non exhaust emissions of pm

pm25_em_petrol_non= (dist_petrol*ICEV_vol * petrol_weight * pm25_non_em_petrol)/g_tonnes
pm25_em_diesel_non = (dist_petrol*ICEV_vol * diesel_weight * pm25_non_em_diesel) /g_tonnes
total_pm25_ICE_non = (pm25_em_petrol_non + pm25_em_diesel_non)

####standardised non exhaust emissions
petrol_pm25_stan_non = pm25_em_petrol_non.div(area_km2,axis=0)
diesel_pm25_stan_non = pm25_em_diesel_non.div(area_km2,axis=0)
total_pm25_stan_non= total_pm25_ICE_non.div(area_km2,axis=0)

mag_pm25 =total_pm25_ICE_non/ total_pm25_ICE_ex
mag_pm25[2050]

## no exhaust emisisons are up to 6 tiems greater than exhaust emissions

"""Total emissions includes exhaust and non exhasut"""

### non standardised emissions
total_pm25_ICE = total_pm25_ICE_ex + total_pm25_ICE_non

#### standardised emissions per 100Km2
total_pm25_ICE_stan = total_pm25_stan_ex + total_pm25_stan_non

### 1. Calculate the change relative to the 2024 baseline (Baseline - Year)
total_pm25_ICE_change = total_pm25_ICE.rsub(total_pm25_ICE[2024], axis=0)
total_pm25_ICE_stan_change = total_pm25_ICE_stan.rsub(total_pm25_ICE_stan[2024], axis=0)

### 2. Drop the 2024 column (which is now all zeros)
total_pm25_ICE_change = total_pm25_ICE_change.drop(columns=[2024])
total_pm25_ICE_stan_change = total_pm25_ICE_stan_change.drop(columns=[2024])

total_pm25_ICE_change

### non standardised emissions
total_pm25_ICE = total_pm25_ICE_ex + total_pm25_ICE_non
## fraction of non exhaust emission
fracnon = total_pm25_ICE_non/total_pm25_ICE
fracnon
## percnet of non ex
percnon = fracnon*100
percnon

"""## BEV"""

#### this is for a 90% regenrative braking, it might be better to use 3 values
# for the three different element of breaking

## emissions in g per year
BEV_pm25_em = (dist_BEV * BEV_vol* pm25_non_em_bev) / g_tonnes

### standardised PM
BEV_pm25_stan = BEV_pm25_em.div(area_km2,axis=0)


#Calculate the change relative to the 2024 baseline (Baseline - Year)
BEV_pm25_em_change = BEV_pm25_em.rsub(BEV_pm25_em[2024], axis=0)
BEV_pm25_stan_change = BEV_pm25_stan.rsub(BEV_pm25_stan[2024], axis=0)

# Drop the 2024 baseline column from each
BEV_pm25_em_change = BEV_pm25_em_change.drop(columns=[2024])
BEV_pm25_stan_change = BEV_pm25_stan_change.drop(columns=[2024])

BEV_pm25_em_change

"""Total PM_25 all vehciles"""

# The 'plus' sign handles the negative BEV values correctly--- this is net change
total_veh_pm25 = total_pm25_ICE_change.add(BEV_pm25_em_change, axis=0)

total_veh_pm25_stan = total_pm25_ICE_stan_change.add(BEV_pm25_stan_change, axis=0)

total_veh_pm25

total_veh_pm25.to_csv("total_veh_pm25.csv")
from google.colab import files
files.download('total_veh_pm25.csv')

"""### NON Exhaust emission Plots"""

# Plotting total  pm emissions across regions, not standardised

key_years = [2025, 2030, 2035, 2040, 2050]
ax = total_veh_pm25[key_years].T.plot(kind='bar', figsize=(12,6))

plt.title('Changed Combined Total Predicted PM2.5 Emissions from fleet, 2024 baseline', fontsize=14)
plt.ylabel('Particulate Matter (Tonnes)/year', fontsize=12)
plt.xlabel('Region', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.legend(title='Year', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()

plt.show()

# Plotting total  pm emissions across regions, not standardised

key_years = [2025, 2030, 2035, 2040, 2050]
ax = BEV_pm25_em_change[key_years].T.plot(kind='bar', figsize=(12,6))

plt.title('Total Predicted PM2.5 Emissions  (2024-2050)', fontsize=14)
plt.ylabel('Particulate Matter (Tonnes)/year/100km2', fontsize=12)
plt.xlabel('Region', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.legend(title='Year', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()

plt.show()

# Plotting total  pm emissions across regions, not standardised

key_years = [2025, 2030, 2035, 2040, 2050]
ax = total_pm25_ICE_change[key_years].T.plot(kind='bar', figsize=(12,6))

plt.title('Total Predicted PM2.5 Emissions change from ICE Vehicles (2024-2050)', fontsize=14)
plt.ylabel('Particulate Matter (Tonnes)/year/100km2', fontsize=12)
plt.xlabel('Region', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.legend(title='Year', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()

plt.show()

"""# Mapping the Data"""

#create a function for this aprt of the code, this shkuld only be for the plotting?

"""https://medium.com/data-science/lets-make-a-map-using-geopandas-pandas-and-matplotlib-to-make-a-chloropleth-map-dddc31c1983d
https://www.datacamp.com/tutorial/geopandas-tutorial-geospatial-analysis
https://www.geeksforgeeks.org/python/geopandas-tutorial/
"""

import geopandas as gdp
map_url="https://github.com/LumumbaAssumani/EV-growth/raw/main/Regions_December_2023_Boundaries_EN_BFE_5329757391006233725.zip"
map_df = gdp.read_file(map_url)

map_df.head()
map_df = map_df.set_index('RGN23NM')

map_df.plot()

## merging data sets together

map_nox = total_nox_ICE_change
merged_nox = map_df.join(map_nox)
map_nox

#### Im now creating aufnction that looks plots all 3 sensitivity ont subplots
year_list = [2030, 2035, 2050]
def EM_maps_range(EM_df,color,main_title):
    EM_merge = map_df.join(EM_df)
    fig, axes = plt.subplots(1, 3, figsize=(15, 8))
    axes = axes.flatten()
    for i, sens in enumerate(year_list):
        ax = axes[i]
        m_min, m_max = EM_merge[sens].min(), EM_merge[sens].max()
        EM_merge.plot(column=sens, cmap=color, linewidth=0.8, ax=ax, edgecolor='0.8')
        ax.axis('off')
        ax.set_title(f'{sens}', fontdict={'fontsize': 14, 'fontweight':'bold'})
        ledg = plt.cm.ScalarMappable(cmap=color, norm=plt.Normalize(vmin= m_min, vmax=m_max))
        ledg._A =[]
        fig.colorbar(ledg,ax=ax, fraction=0.046, pad=0.04)
    fig.suptitle(main_title, fontsize=20, fontweight='bold', y=0.98)
    fig.text(0.05, 0.05, 'Source: DEFRA COST VALUES' , ha='left', fontsize=12, color='#555555')
    plt.tight_layout()
    plt.show()

year_list = [2030, 2035, 2050]
def EM_maps_range1(EM_df, color, main_title):
    EM_merge = map_df.join(EM_df)

    fig, axes = plt.subplots(1, 3, figsize=(10, 8))
    axes = axes.flatten()

    vmin = EM_merge[year_list].min().min()
    vmax = EM_merge[year_list].max().max()

    for i, sens in enumerate(year_list):
        ax = axes[i]
        EM_merge.plot(column=sens, cmap=color, linewidth=0.8, ax=ax, edgecolor='0.8', vmin=vmin, vmax=vmax)
        ax.axis('off')
        ax.set_title(f'{sens}', fontdict={'fontsize': 14, 'fontweight': 'bold'})

    # CHANGED: manually create a new axis just for the colourbar
    cbar_ax = fig.add_axes([0.92, 0.15, 0.02, 0.6])  # [left, bottom, width, height]
    ledg = plt.cm.ScalarMappable(cmap=color, norm=plt.Normalize(vmin=vmin, vmax=vmax))
    ledg._A = []
    fig.colorbar(ledg, cax=cbar_ax)

    # CHANGED: manually adjust right margin to make room for colourbar
    plt.subplots_adjust(right=0.9)

    fig.suptitle(main_title, fontsize=20, fontweight='bold', y=0.98)
    fig.text(0.05, 0.05, 'Source: DEFRA COST VALUES', ha='left', fontsize=12, color='#555555')
    plt.show()

#EM_maps_range1(nox_total_change_stan,'Oranges','Change in Absolute NOx Emissions (Tonnes/Year) vs 2024 Baseline Standardised')
#EM_maps_range1(total_veh_pm25_stan,'Blues','Change in Absolute Pm2.5 Emissions (Tonnes/Year) vs 2024 Baseline Standardised')

#EM_maps_range(total_nox_ICE_change,'Oranges','Change in Absolute NOx Emissions (Tonnes/Year) vs 2024 Baseline')
#EM_maps_range(total_veh_pm25,'Blues','Change in Absolute Pm2.5 Emissions (Tonnes/Year) vs 2024 Baseline')

#EM_maps_range(nox_total_change_stan,'Oranges','Change in Absolute NOx Emissions (Tonnes/Year) vs 2024 Baseline Standardised')
#EM_maps_range(total_veh_pm25_stan,'Blues','Change in Absolute Pm2.5 Emissions (Tonnes/Year) vs 2024 Baseline Standardised')

year_list = [2030, 2035, 2050]

def EM_maps_range3(EM_df, color, filename_prefix):
    EM_merge = map_df.join(EM_df)

    fig, axes = plt.subplots(1, 3, figsize=(14, 5))
    axes = axes.flatten()

    vmin = EM_merge[year_list].min().min()
    vmax = EM_merge[year_list].max().max()

    for i, sens in enumerate(year_list):
        ax = axes[i]
        EM_merge.plot(column=sens, cmap=color, linewidth=0.8, ax=ax, edgecolor='0.8', vmin=vmin, vmax=vmax)
        ax.axis('off')
        ax.set_title(f'{sens}', fontdict={'fontsize': 19, 'fontweight': 'bold'})

        north_arrow(
            ax,
            location="upper left",
            rotation={"crs": EM_merge.crs, "reference": "center"}
        )

    # Colourbar scaled relative to the axes height
    fig.subplots_adjust(left=0.01, right=0.88, top=0.95, bottom=0.08, wspace=0.05)
    cbar_ax = fig.add_axes([0.90, 0.08, 0.02, 0.87])
    ledg = plt.cm.ScalarMappable(cmap=color, norm=plt.Normalize(vmin=vmin, vmax=vmax))
    ledg._A = []
    fig.colorbar(ledg, cax=cbar_ax)

    # Save as PDF
    fig.savefig(f'{filename_prefix}.jpeg', format='jpeg', bbox_inches='tight')
    plt.show()

EM_maps_range3(total_nox_ICE_change,'Oranges', 'Nox_ex_map')
EM_maps_range3(total_veh_pm25,'Blues','PM2.5_ex_map')
EM_maps_range3(nox_total_change_stan,'Oranges', 'Noxstanmap')
EM_maps_range3(total_veh_pm25_stan,'Blues','PMstanmap')

"""#Calculating Costs

The discount factor can be calculated using the discount rate as follows:

$$DF = \frac{1}{(1 + DR)^T}$$

where:
* **DF** = discount factor
* **DR** = discount rate
* **T** = number of years

## Setting up the basis for coding for later calculations later.
"""

year_2024 = 103.84
year_2025 = 107.35
ratio = year_2024/year_2025
print(ratio)

### disocunting the price
year_range = np.arange(2025,2050+1)
year_range

disc_array =[]
dr=1.5/100


for year in year_range:
  n_years= year-2024
  dis_f = 1/((1+dr)**n_years)
  dis_f = round(dis_f,3)
  disc_array.append(dis_f)

disc_array

# NOX cost factos
### sector source, this is for road transport units are in pounds

# NOx Scenario Data
nox_data = {
    'Scenario': ['Low', 'Central', 'High'],
    'Cost': [2004.00, 13631.00, 46863.00]
}

nox_cost_df = pd.DataFrame(nox_data)
nox_cost_df = nox_cost_df.set_index('Scenario')
nox_cost_df = nox_cost_df.mul(ratio, axis=0)
nox_cost_df

#print("NOx Road Transport Costs:")
#print(nox_cost_df)

# NOX cost factos
### sector source, this is for road transport units are in pounds

# NOx Scenario Data
pm_25_data = {
    'Scenario': ['Low', 'Central', 'High'],
    'Cost': [2004.00, 13631.00, 46863.00]
}

pm25cost_df = pd.DataFrame(pm_25_data)
pm25cost_df = pm25cost_df.set_index('Scenario')
pm25cost_df = pm25cost_df.mul(ratio, axis=0)
pm25cost_df

#print("NOx Road Transport Costs:")
#print(nox_cost_df)

"""## Calculating the costs of the Emissions (change in Absolute)"""

pm25change = total_veh_pm25
#pm25change = abs(pm25change)

def cost_impact(costdf,emchange, scenario):
    # Grab the single cost value
    rebased_cost = costdf.loc[scenario, 'Cost']
    ud_benefit = emchange * rebased_cost
    d_benefit = ud_benefit.mul(disc_array, axis=1)
    npv = (d_benefit.sum(axis=1))
    return npv

# NOW call it
nox_low_npv = cost_impact(nox_cost_df,total_nox_ICE_change, 'Low')
nox_central_npv = cost_impact(nox_cost_df,total_nox_ICE_change, 'Central')
nox_high_npv = cost_impact(nox_cost_df,total_nox_ICE_change, 'High')

pm25_low_npv = cost_impact(pm25cost_df,pm25change, 'Low')
pm25_central_npv = cost_impact(pm25cost_df,pm25change ,'Central')
pm25_high_npv = cost_impact(pm25cost_df,pm25change, 'High')

# Create a quick ranking of regions by total health benefit

# 2. Combine these into a single Summary Table
nox_summary_df = pd.DataFrame({
    ' NPV Low (£)': nox_low_npv,
    ' NPV Central (£)': nox_central_npv,
    ' NPV High (£)': nox_high_npv
})

nox_summary_3sf = (nox_summary_df.map(lambda x: float(f'{x:.3g}')))/ (10**6)

# Display your final result
print(nox_summary_3sf)

nox_summary_3sf_tot = nox_summary_3sf.sum(axis=0)
nox_summary_3sf_tot/25

pm25_sumamry_df = pd.DataFrame({
    ' NPV Low (£)' : pm25_low_npv,
    ' NPV Central (£)' : pm25_central_npv,
    ' NPV High (£)' : pm25_high_npv
})

pm25_summary_3sf = (pm25_sumamry_df.map(lambda x: float(f'{x:.3g}')))/ (10**6)

# Display your final result
print(pm25_summary_3sf)

"""### Mapping the costs"""

#### Im now creating aufnction that looks plots all 3 sensitivity ont subplots

def cost_maps_range(cost_df,color,main_title):
    cost_merge = map_df.join(cost_df)
    fig, axes = plt.subplots(1, 3, figsize=(12, 6))
    axes = axes.flatten()
    for i, sens in enumerate(cost_df.columns):
        ax = axes[i]
        m_min, m_max = cost_merge[sens].min(), cost_merge[sens].max()
        cost_merge.plot(column=sens, cmap=color, linewidth=0.8, ax=ax, edgecolor='0.8')
        ax.axis('off')
        ax.set_title(f'{sens}', fontdict={'fontsize': 14, 'fontweight':'bold'})
        ledg = plt.cm.ScalarMappable(cmap=color, norm=plt.Normalize(vmin= m_min, vmax=m_max))
        ledg._A =[]
        fig.colorbar(ledg,ax=ax, fraction=0.046, pad=0.04)
    fig.suptitle(main_title, fontsize=14, fontweight='bold', y=0.98)
    fig.text(0.05, 0.05, 'Source: DEFRA COST VALUES' , ha='left', fontsize=12, color='#555555')
    plt.tight_layout()
    plt.show()

cost_maps_range(nox_summary_3sf,'Oranges','Sensitivity NPV costs for Nox emissions between 2024 and 2050 per 100,000 residents')
cost_maps_range(pm25_summary_3sf,'Blues','Sensitivity NPV costs for PM2.5 emissions  between 2024 and 2050 per 100,000 residents')



"""# Health metrics

## Methodology

> Has health metric tables from DEFRA COST DAMAGE APPROACH
"""

#### health metrics for sensitivity analysis - Nox

# Health metrics data for NOx (per tonne emitted)
# Source: Defra Cost Damage Approach, Section 6.2 (Tables 12, 13, and 14)
nox_health_metrics = {

    "low_sensitivity": {
        "lyl": 0.43,
        "qalys": 0.0092,
        "HA": 0.0026
    },

    "central": {
        "lyl": 0.11,
        "qalys": 0.070,
        "HA": 0.0044
    },


    "high_sensitivity": {
        "lyl": 0.21,
        "qalys": 0.22,
        "HA": 0.012
    }
}


nox_hm = pd.DataFrame(nox_health_metrics)

nox_hm

pm25_health_metrics = {

    "low_sensitivity": {
        "lyl": 1.0,
        "qalys": 0.17,
        "HA": -0.020
    },
    "central": {
        "lyl": 1.4,
        "qalys": 0.60,
        "HA": 0.030
    },

    "high_sensitivity": {
        "lyl": 1.5,
        "qalys": 2.6,
        "HA": 0.098
    }
}

pm25_hm = pd.DataFrame(pm25_health_metrics)
pm25_hm



total_tonnes = total_nox_ICE_change.sum(axis=1)
average = total_tonnes.mean()
average

total_tonnes

### 2024 baseline of Nox
Nox2024UK = 0.16387899234463688 * (10**6)
Nox2024UK



"""### Creating a function for health"""

def create_health_summary1(emissions_df, sensitivity):


    total_tonnes = emissions_df.sum(axis=1)

    factors = pd.Series(nox_health_metrics[sensitivity])

    # Use broadcasting: Multiply the column of tonnes by the row of factors
    # We use .apply(lambda x: x * factors) or simple multiplication if indices align
    summary = total_tonnes.apply(lambda x: x * factors)

    # 3. Normalize by population
    summary = summary.div(reg_pop,axis=0)* 100000

    # 4. Clean up with 3 Significant Figures
    return summary.map(lambda x: float(f"{x:.3g}"))

# This should now run without the TypeError
Nox_low_hm = create_health_summary1(total_nox_ICE_change, 'low_sensitivity')
Nox_central_hm = create_health_summary1(total_nox_ICE_change, 'central')
Nox_high_hm = create_health_summary1(total_nox_ICE_change, 'high_sensitivity')

## PM Hm
pm25_low_hm = create_health_summary1(pm25change, 'low_sensitivity')
pm25_central_hm = create_health_summary1(pm25change, 'central')
pm25_high_hm = create_health_summary1(pm25change, 'high_sensitivity')

total_nox = total_nox_ICE_change.sum(axis=1)
total_nox

total_pm25change = pm25change.sum(axis=1)
total_pm25change

Nox_central_hm

pm25_central_hm

pmlost = pm25_central_hm['lyl'].mean()
pmlost

def create_health_summary(emissions_df, metric_name):
    # 1. Calculate the Total Tonnes of NOx reduced per region
    total_tonnes = emissions_df.sum(axis=1)

    # 2. Reach into the dictionary for each sensitivity to find the specific metric
    summary = pd.DataFrame({
        'Low Sensitivity': total_tonnes * nox_health_metrics['low_sensitivity'][metric_name],
        'Central': total_tonnes * nox_health_metrics['central'][metric_name],
        'High Sensitivity': total_tonnes * nox_health_metrics['high_sensitivity'][metric_name]
    }, index=emissions_df.index)

    summary = summary.div(reg_pop*100000,axis=0)

    # 3. Clean up with 3 Significant Figures
    return summary.map(lambda x: float(f"{x:.3g}"))

# --- Now these calls will work perfectly ---
lyl_summary_nox = create_health_summary(total_nox_ICE_change, 'lyl')
qaly_summary_nox = create_health_summary(total_nox_ICE_change, 'qalys')
hosp_summary_nox = create_health_summary(total_nox_ICE_change, 'HA')


lyl_summary_pm25 = create_health_summary((pm25change), 'lyl')
qaly_summary_pm25 = create_health_summary((pm25change), 'qalys')
hosp_summary_pm25= create_health_summary((pm25change), 'HA')

lyl_summary_pm25



"""https://www.gov.uk/government/statistics/transport-and-environment-statistics-2023/transport-and-environment-statistics-2023

https://www.gov.uk/csv-preview/69832840afabc06c35d343c2/fig07_nitrogen_oxides_key_emission_sources.csv

## Maps for Health Metrics
"""

import matplotlib.pyplot as plt

def hm_maps_combined(h_df, filename, color='viridis'):
    # Join geometry
    hm_merge = map_df.join(h_df)

    # 1. Reduced distance: wspace=0 pulls them tightly together
    fig, axes = plt.subplots(1, 3, figsize=(18, 8), gridspec_kw={'wspace': 0.05})

    title_mapping = {
        'lyl': 'LYL saved',
        'qalys': 'QALYs Saved',
        'HA': ' HA saved'
    }

    for i, col in enumerate(h_df.columns):
        ax = axes[i]
        m_min, m_max = hm_merge[col].min(), hm_merge[col].max()

        # Plot
        hm_merge.plot(column=col, cmap=color, linewidth=0.5, ax=ax, edgecolor='0.3')
        ax.axis('off')

        # 2. Add North Arrow using your specific logic
        # Assuming north_arrow is available in your namespace
        north_arrow(
            ax,
            location="upper left",
            rotation={"crs": hm_merge.crs, "reference": "center"}
        )

        # 3. Titles and Individual Scales
        clean_title = title_mapping.get(col, col.upper())
        ax.set_title(clean_title, fontsize=22, fontweight='bold')

        sm = plt.cm.ScalarMappable(cmap=color, norm=plt.Normalize(vmin=m_min, vmax=m_max))
        sm._A = []
        # pad=0.01 keeps the colorbar very close to the map
        cbar = fig.colorbar(sm, ax=ax, fraction=0.03, pad=0.01)
        cbar.ax.tick_params(labelsize=13)

    #fig.suptitle(main_title, fontsize=20, fontweight='bold', y=0.98)

    # 4. Save the plot
    # dpi=300 for high resolution, bbox_inches='tight' ensures no clipping
    fig.savefig(f'{filename}.jpeg', format='pdf', bbox_inches='tight')
    plt.tight_layout()
    plt.show()

# Execute
hm_maps_combined(Nox_low_hm ,'Hmnoxlow' , color='viridis_r')
hm_maps_combined(Nox_central_hm, 'Hmnoxcen', color='viridis_r')
hm_maps_combined(Nox_high_hm, 'Hmnoxhigh',color='viridis_r')

hm_maps_combined(pm25_low_hm, 'hmpm25low', color='viridis_r')
hm_maps_combined(pm25_central_hm, 'hmpm25cen',color='viridis_r')
hm_maps_combined(pm25_high_hm, 'hmpm25high', color='viridis_r')

#### Im now creating aufnction that looks plots all 3 sensitivity ont subplots
def hm_maps_range(h_df,color,main_title):
    hm_merge = map_df.join(h_df)
    fig, axes = plt.subplots(1, 3, figsize=(16, 6))
    axes = axes.flatten()
    for i, sens in enumerate(h_df.columns):
        ax = axes[i]
        m_min, m_max = hm_merge[sens].min(), hm_merge[sens].max()
        hm_merge.plot(column=sens, cmap=color, linewidth=0.8, ax=ax, edgecolor='0.8')
        ax.axis('off')
        ax.set_title(f'{sens}', fontdict={'fontsize': 14, 'fontweight':'bold'})
        ledg = plt.cm.ScalarMappable(cmap=color, norm=plt.Normalize(vmin= m_min, vmax=m_max))
        ledg._A =[]
        fig.colorbar(ledg,ax=ax, fraction=0.046, pad=0.04)
    fig.suptitle(main_title, fontsize=20, fontweight='bold', y=0.98)
    fig.text(0.05, 0.05, 'Source: DEFRA Health metrics, 201' , ha='left', fontsize=12, color='#555555')
    plt.tight_layout()
    plt.show()

### NOX EMISSIONS MAPS
# hm_maps_range(lyl_summary_nox,'Blues', "NOx emisisons 2024-2050: Life Years Lost ")
# hm_maps_range(qaly_summary_nox,'Purples',"NOx emisisons 2024-2050: Quality-Adjusted-Life Years")
# hm_maps_range(hosp_summary_nox,'PuRd', "NOx emisisons 2024-2050: Hospital Admissions")
# Nox_hm_maps = [lyl_summary_nox,qaly_summary_nox,hosp_summary_nox]

# hm_maps_range(lyl_summary_pm25,'Blues', "PM2.5 emisisons 2024-2050: Life Years Lost  per 100,000 residents")
# hm_maps_range(qaly_summary_pm25,'Purples',"PM2.5 emisisons 2024-2050: Quality-Adjusted-Life Years per 100,000")
# hm_maps_range(hosp_summary_pm25,'PuRd', "PM2.5 emisisons 2024-2050: Hospital Admissions per 100,000 residents")
# pm25_hm_maps = [lyl_summary_pm25,qaly_summary_pm25,hosp_summary_pm25]

