# -*- coding: utf-8 -*-
"""S_Curve_forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pi-Ao01orROyibbMLRxg502yd4nzYgSt
"""

# preamble
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""# Battery Licensced Data"""

## reading the file

url1 = "https://github.com/LumumbaAssumani/EV-growth/raw/main/Licensed_PIV.csv"
df = pd.read_csv(url1, header=4)
df = df.drop(columns=['Units', 'ONS Sort'], axis=1).copy()

## filtering the data using booleans
df = df[(df['BodyType']== "Cars") &
        (df['Keepership']== "Total") &
        (df['Fuel']== "BATTERY ELECTRIC") &
        (df['ONS Code'].str.contains("E12", case= False, na=False))].copy()

#df = df.drop(labels='Keepership', axis=1)

df = pd.melt(
    df,
    id_vars=df.columns[:5],    # The "anchor" columns (0 through 4)
    value_vars=df.columns[5:]  # The columns to "unpivot" (5 to the end)
)
df

## renaming columns, creating a datetime format and  setting year to index
df.rename(columns={'variable': 'year'}, inplace=True)
df['year'] = df['year'].str.replace(r'(\d{4})\s(Q\d)', r'\1-\2', regex=True)
df['year'] = pd.to_datetime(pd.PeriodIndex(df['year'], freq='Q').to_timestamp())
df = df.set_index('year')
df['value'] = df['value'].replace({',': ''}, regex=True).astype(float,errors='ignore')
df

# Returns the first column as a Series
first_col = df.iloc[:, 0]

pivot_df = df.pivot(columns='ONS Geography', values='value')
BLEV=pivot_df.astype(float)
BLEV

## indexing to choose start and end of index
startTrain = pd.to_datetime('2011-10-01', yearfirst=True)
endTrain = pd.to_datetime('2024-10-01',yearfirst=True)

# This selects all rows between the start and end dates/years
BLEV = BLEV.loc[startTrain:endTrain].copy()

df.to_csv("licensced_battery_electric.csv")

"""# Total licensced vehicles"""

url2 = "https://github.com/LumumbaAssumani/EV-growth/raw/main/total_Licensced_vehicles.csv"
df2 = pd.read_csv(url2, header =4)

df2 = df2[(df2['BodyType']== "Cars") &
        (df2['Keepership']== "Total") &
        (df2['Fuel']== "Total") &
        (df2['ONS Code'].str.contains("E12", case= False, na=False))]

df2 = df2.drop(columns=['Units', 'ONS Sort'])

df2 = pd.melt(
    df2,
    id_vars=df2.columns[:5],    # The "anchor" columns (0 through 4)
    value_vars=df2.columns[5:]  # The columns to "unpivot" (5 to the end)
).copy()

df2

df2copy = df2.copy()

df2copy['value'] = df2copy['value'].replace({',': ''}, regex=True).astype(float,errors='ignore')

# Multiply by a thousand because the units of the raw data is thousands
df2copy['value']= (df2copy['value']*1000)

df2copy.rename(columns={'variable': 'year'}, inplace=True)
df2copy['year'] = df2copy['year'].str.replace(r'(\d{4})\s(Q\d)', r'\1-\2', regex=True)
df2copy['year'] = pd.to_datetime(pd.PeriodIndex(df2copy['year'], freq='Q').to_timestamp())
df2copy = df2copy.set_index('year')

pivot_df2 = df2copy.pivot(columns='ONS Geography', values='value')
TLV = pivot_df2.astype(float)
TLV = TLV.loc[startTrain:endTrain].copy()
TLV

## quick check of number of lienscd cars in baseline
TLV.iloc[-1].sum()

#from google.colab import files
#files.download('TLV.csv')
TLV.to_csv("TLV.csv")

"""# Performing S curve analysis"""

# This treats all shared columns as a single combined key
share = (BLEV/TLV)
merg_percent =  share*100
share.describe()

share = share.rename(columns={'East': 'East of England'})
share

"""Historic share of BECS"""

sns.set_style("white")

# Pass the multiplied DataFrame directly; Seaborn handles the rest
plt.figure(figsize=(10,8))
plt.xlabel('Year', fontsize =12)
plt.ylabel(' Share of BEC (%)', fontsize = 12)
plt.title('Historic share of BECs by region in England ',fontweight ='bold', size = 16)
sns.lineplot(data=share * 100,dashes=False, linewidth= 2)
plt.savefig('Historic_share_BECs.jpeg', dpi=300, bbox_inches='tight')
plt.show()

"""## S-CURVE"""

Linear_df=np.log((share)/(1-share))
base=Linear_df.index[0].year
Target = 2050.25
n_periods = int((Target - base)*4)
Linear_df

time_num = np.arange(len(Linear_df.index))
[coeffs, cov_matrix] = np.polyfit(time_num, Linear_df, 1, cov = True)

m_arr = coeffs[0] ## gradient (m)
c_arr = coeffs[1] ## y intercept c
m_stderr = np.sqrt(cov_matrix[0, 0])  # uncertainty on slope (standard error)
C_stderr = np.sqrt(cov_matrix[1, 1])  # uncertainty on intercept (standard error)

print(m_stderr,C_stderr)

print(m_arr, c_arr)

# sensitivity of my slope
m_slow    = m_arr - m_stderr
m_central = m_arr
m_fast    = m_arr + m_stderr

# generate three S-curve projections
k = 0.85 # from Rp

def make_scurve(m, c, k, n_periods):
    return pd.DataFrame(
        [k / (1 + np.exp(-(m * j + c))) for j in range(n_periods)],
        columns=share.columns
    )

s_slow    = make_scurve(m_slow,    c_arr, k, n_periods)
s_central = make_scurve(m_central, c_arr, k, n_periods)
s_fast    = make_scurve(m_fast,    c_arr, k, n_periods)

## identifying start date from historical data
start_date = Linear_df.index[0]
freq = pd.infer_freq(Linear_df.index)
forecast_dates = pd.date_range(start=start_date, periods=len(s_central), freq=freq)

# assign date index
s_slow.index    = forecast_dates
s_central.index = forecast_dates
s_fast.index    = forecast_dates

s_slow.tail(60)

plt.figure(figsize=(12,8))
plt.xlabel('Year', fontsize =12, fontweight ='bold')
plt.ylabel(' Share of EV (%)', fontsize=12,fontweight = 'bold')
plt.title(' Share Battery Electric Cars between 2011 to 2050',fontweight ='bold', size = 16)

for col in s_central:
  plt.plot(s_central.index.values,s_central[col])
  plt.legend(s_central.columns)

plt.show()
plt.savefig('EV_S_Curve_jpg', dpi=300, bbox_inches='tight')

import matplotlib.pyplot as plt
import numpy as np
import matplotlib.dates as mdates

COLORS = ['#e41a1c','#377eb8','#4daf4a','#984ea3',
          '#ff7f00','#a65628','#f781bf','#999999','#dede00']

fig, axes = plt.subplots(3, 3, figsize=(10, 8), sharey=True, sharex=True)

for i, (ax, region) in enumerate(zip(axes.flatten(), share.columns)):
    c      = COLORS[i]
    cent   = s_central[region].values
    slow   = s_slow[region].values
    fast   = s_fast[region].values
    quarters = pd.period_range(start='2011Q4', periods=n_periods, freq='Q')
    years = quarters.to_timestamp()


    # plot
    ax.fill_between(years, slow, fast, alpha=0.25, color='lightsteelblue')
    ax.plot(years, cent, color=c, linewidth=2)
    ax.plot(years, slow, color=c, linewidth=0.8, linestyle='--')
    ax.plot(years, fast, color=c, linewidth=0.8, linestyle='--')
    ax.axhline(0.85, color='black', linewidth=0.7, linestyle='--', alpha=0.5)

    # compute stats
    yr_50 = quarters[np.argmax(cent >= 0.50)].strftime('%Y Q%q') if any(cent >= 0.50) else 'N/A'
    yr_85 = quarters[np.argmax(cent >= 0.84)] if any(cent >= 0.84) else 'N/A'
    spread  = round(np.mean(fast - slow), 3)

    # inside your loop, replace the legend and tick lines with:

    ax.legend(
    title=f"50%:  {yr_50}\n85%:  {yr_85}\nSpread:  {spread}",
    handles=[], loc='upper left', fontsize=11,
    framealpha=0.9,
    prop={'weight': 'bold', 'size': 11},
    title_fontproperties={'weight': 'bold', 'size': 11}
)

    ax.set_title(region, fontsize=13, fontweight='bold', pad=6)
    ax.tick_params(labelsize=10)
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y,_: f'{int(y*100)}%'))
    ax.xaxis.set_major_locator(mdates.YearLocator(10))  # every 10 yrs, less crowding
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
    plt.setp(ax.xaxis.get_majorticklabels(), rotation=0, fontsize=10)  # flat, not rotated

    ax.grid(True, linestyle='--', linewidth=0.5, alpha=0.5, color='grey')
    ax.set_axisbelow(True)  # keeps grid behind the curves

# outside loop, replace fig.text lines with:
fig.text(0.5, 0.01, 'Year', ha='center', fontsize=14, fontweight='bold')
fig.text(0.01, 0.5, 'BEV Share (%)', va='center', rotation='vertical',
         fontsize=14, fontweight='bold')
#plt.suptitle('BEV Fleet Share — Regional S-Curve Projections',
           #  fontsize=16, fontweight='bold', y=1.01)

plt.tight_layout(pad=2.0)  # slightly more padding between panels
plt.savefig('BEVShare.pdf', dpi=300, bbox_inches='tight')
plt.show()

s_df = s_central
s_df

#printing out_csv
scurves=s_df.to_csv('s_region_df.csv')

from google.colab import files
files.download('s_region_df.csv')

"""# Erros and uncertainity MAPES"""

from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

from sklearn.metrics import r2_score

# np.outer multiplies the time array by each region's slope
y_predict = np.outer(time_num, m_arr) + c_arr
y_actual = Linear_df.values

# Calculating the R2 score for each region
r2_results = r2_score(y_actual, y_predict, multioutput='raw_values')
r2_results = r2_results.round(3)


r2_summary = pd.DataFrame({
    'Region': Linear_df.columns,
    'R2_Score': r2_results
})

print(r2_summary)

# Calculate SSE for each region (summing down the time axis)

sse_per_region = np.sum(( y_actual-y_predict)**2, axis=0)

sse_per_region = sse_per_region.round(3)

# To make it readable, wrap it in a Series with the region names

sse_summary = pd.Series(sse_per_region, index=Linear_df.columns)
sse_summary

fig, axes = plt.subplots(3, 3, figsize=(10, 8), sharex=True)
axes = axes.flatten()

for i, region in enumerate(Linear_df.columns):
    # Plot Actual data points
    axes[i].scatter(time_num, Linear_df[region], color='blue', alpha=0.5, label='Actual (Linearised)', s = 13)

    # Plot Predicted trendline
    axes[i].plot(time_num, y_predict[:, i], color='red', linewidth=2, label='Model Trend')

    # SSE and R² values
    current_sse = sse_per_region[i]
    current_r2  = r2_results[i]

    # Region name only in title
    axes[i].set_title(f"{region}", fontsize=11, fontweight='bold')

    # Formatting
    axes[i].grid(True, linestyle='--', alpha=0.6)
    if i >= 6: axes[i].set_xlabel('End Quarters 2011 Q4 to 2024 Q4', fontweight='bold', fontsize=9)
    if i % 3 == 0: axes[i].set_ylabel('ln(f / 1-f)', fontweight='bold', fontsize=9)
    axes[i].tick_params(axis='both', which='major', labelsize=8)

    # SSE and R² as dedicated legend entries
    axes[i].plot([], [], ' ', label=f'SSE: {current_sse:.3f}')
    axes[i].plot([], [], ' ', label=f'R²:  {current_r2:.3f}')

    axes[i].legend(fontsize=9.5, loc='upper left', framealpha=0.7)
plt.tight_layout()
plt.savefig('Linear.pdf', dpi=300, bbox_inches='tight')
plt.show()

"""## Actual vs predicted"""

# Calculating MAPE
y_actualshare  = share.values
y_predictshare = s_central.iloc[:len(share)].values
mape_array = 100 * np.mean(
    np.abs(( y_actualshare-y_predictshare) / y_actualshare), axis=0)
mape_series = pd.Series(mape_array.round(3), index=share.columns, name='MAPE (%)')


fig, axes = plt.subplots(3, 3, figsize=(10, 8), sharex=True, sharey=True)
axes = axes.flatten()


for i, region in enumerate(share.columns):
    ax = axes[i]

    # Grab the data
    actual  = share[region] * 100
    predict = s_central[region].iloc[:len(share)] * 100
    x_vals  = Linear_df.index.values

    # Lookup the MAPE
    current_mape = mape_series[region]

    # Plotting
    ax.plot(x_vals, actual,  label='Actual',    marker='o', linestyle='dashed',
            linewidth=1.5, markersize=3)
    ax.plot(x_vals, predict, label='Predicted', marker='o', linestyle='dashed',
            linewidth=1.5, markersize=3)
    ax.fill_between(x_vals, actual, predict, alpha=0.25, color='lightsteelblue')

    # Title per subplot
    ax.set_title(f'{region}', fontsize=11, fontweight='bold')

    # Tick size
    ax.tick_params(axis='both', which='major', labelsize=10.5)

    # Legend with MAPE
    ax.legend(title=f'MAPE: {current_mape}%', title_fontsize=12, fontsize=8,
              loc='upper left', framealpha=0.7)

# Shared axis labels
fig.text(0.5,  0.01, 'Historic Timeline in Years', ha='center', fontsize=11)
fig.text(0.01, 0.5,  'Share of EV %', va='center', rotation='vertical', fontsize=11)

# Clean up layout and display
plt.tight_layout(rect=[0.03, 0.03, 1, 1])
plt.savefig('ev_share_plot.pdf', dpi=300, bbox_inches='tight')
plt.show()